remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: SO Linguistics
description: This website provides information regarding the Science Olympiad New Idea Linguistics and posts Linguistics tests written by the Linguistics team for competitions.
